### ISSUE TITLE
ES6与未来中第二章语法发现一处疑问。

### ISSUE THREAD

**Issue by fzhw88** [JoeHetfield/You-Dont-Know-JS#4]
在“块儿作用于的函数”这个部分有这样一个例子：

if (something) {
	function foo() {
		console.log( "1" );
	}
}
else {
	function foo() {
		console.log( "2" );
	}
}

foo();			// ??

后面的解释“在前ES6环境下，无论something的值是什么foo()都将会打印"2"，因为两个函数声明被提升到了块儿的顶端，而且总是第二个有效。”真的是这样吗？我测试了一下，去掉两组花括号（块作用域消失，语义上正好等价于ES5环境），something用true来替换，运行的结果是1.

看了一下英文的原文也是这样，是作者错了还是我的测试方法有误？因为我的英文不好，就不去原版发issues了，在这里求大神指点。

**Comment by JoeHetfield** [comment]
如果你想得到文章中描述的结果，可使用IE，在控制台中切换到 IE10 版本（更早版本也应该一样），然后运行程序。如果是 IE11 以及其他主流现代浏览器，已经完全支持 ES6 了，所以得不到结果 “2”。

另外，如你所说的去掉花括号：

    if (something) 
        function foo() {
            console.log( "1" );
        }
    else 
        function foo() {
            console.log( "2" );
        }
    foo();	// ??

我在 IE11 中得到 “2”， 而在 chrome 中得到 “1”，我想这可能是因为两个浏览器对块儿作用域的解释上有所不同。
