### ISSUE TITLE
一些链接404，或是markdown语法问题

### ISSUE THREAD

**Issue by zxhycxq** [JoeHetfield/You-Dont-Know-JS#5]
**第七章：元编程**
![image](https://user-images.githubusercontent.com/11674203/33525790-90296382-d871-11e7-9b6b-9c9f48cd07c3.png)
**第八章：ES6以后**
![image](https://user-images.githubusercontent.com/11674203/33525828-ef53eb34-d871-11e7-8617-37c36cbb9a69.png)

**Comment by JoeHetfield** [comment]
Do you mean the markdown for the links? 
Yup, sorry for that, will fix it later.

**Comment by JoeHetfield** [comment]
啊，是的，markdown 写的有问题，我会修复它们的
